### ISSUE TITLE
Dashboard /order unfinished vs design

### ISSUE THREAD

**Issue by seacurrent** [tabetalt/backoffice#107]
Add header according to design. 

Ignore following features in design:
Filter
Search
Export

**Comment by AnneMatilde** [comment]
Design: https://xd.adobe.com/view/a860bd35-ae7e-4244-89b8-e453963dae13-fd33/
Page: Tabetalt - Admin - Ordre/kunder

**Comment by Keitarofreeman** [comment]
Done PR: https://github.com/tabetalt/backoffice/pull/125
