### ISSUE TITLE
Dashboard "Show order" create according to design

### ISSUE THREAD

**Issue by seacurrent** [tabetalt/backoffice#108]
In the dashboard under the menuitem "Ordre/kunder" you have a listing of all purchases. On the rightside you can click for more info about a single purchase. 

Next page needs to be created.

**Comment by AnneMatilde** [comment]
Design: https://xd.adobe.com/view/a860bd35-ae7e-4244-89b8-e453963dae13-fd33/
Page: Tabetalt - Admin - Ordre/kunder – 1

**Comment by AnneMatilde** [comment]
Design for ordre page is now updated:
![image](https://user-images.githubusercontent.com/54155334/118249866-24ce4200-b4a6-11eb-8a1f-c5e35617ed52.png)

**Comment by Keitarofreeman** [comment]
Done PR: https://github.com/tabetalt/backoffice/pull/125
