### ISSUE TITLE
Add Product not working

### ISSUE THREAD

**Issue by seacurrent** [tabetalt/backoffice#111]
Not possible to add a new product

**Comment by AnneMatilde** [comment]
![image](https://user-images.githubusercontent.com/54155334/116446597-65e41680-a857-11eb-93f1-72eb4bc76e6e.png)

Fail message appears when clicking "Lagre".

**Comment by AnneMatilde** [comment]
This also links to this #55

**Comment by Keitarofreeman** [comment]
Fixed. PR https://github.com/tabetalt/backoffice/pull/101
