### ISSUE TITLE
Hide Dashboard menu item 

### ISSUE THREAD

**Issue by seacurrent** [tabetalt/backoffice#112]

**Comment by AnneMatilde** [comment]
![image](https://user-images.githubusercontent.com/54155334/116447367-3386e900-a858-11eb-8b84-5667304116ac.png)

**Comment by AnneMatilde** [comment]
Please move "log out" to new icon next to "Emil Walter" down in the left corner. 
![image](https://user-images.githubusercontent.com/54155334/117297014-fe8d1e80-ae75-11eb-855b-9bd3bbe11a21.png)

**Comment by Keitarofreeman** [comment]
Done. PR: https://github.com/tabetalt/backoffice/pull/115
