### ISSUE TITLE
Create font viewing component

### ISSUE THREAD

**Issue by cobraz** [tabetalt/backoffice#42]
<img width="736" alt="Skjermbilde 2020-09-20 kl  01 07 38" src="https://user-images.githubusercontent.com/3726815/93690842-af100300-fadd-11ea-9dd6-fe33b883b1b8.png">

**Comment by TanyaDolgopolova** [comment]
@cobraz I think this component need to be created in **Kit** project and refer to it already in this project. How do you like this idea?

**Comment by cobraz** [comment]
Yes :D
