### ISSUE TITLE
Add theme chooser

### ISSUE THREAD

**Issue by cobraz** [tabetalt/backoffice#44]
<img width="832" alt="Skjermbilde 2020-09-20 kl  01 08 51" src="https://user-images.githubusercontent.com/3726815/93690865-da92ed80-fadd-11ea-8b49-9f6e726f9052.png">

**Comment by TanyaDolgopolova** [comment]
@cobraz I see that this logic for selecting is similar with issue #42. I think that we can create component with box and two buttons and add highlighting of selected item in the **KIT project**. With that we will be have possibility for code reusing. What do you think?

**Comment by cobraz** [comment]
Nice idea! Let's do that!
