### ISSUE TITLE
Delivery methods

### ISSUE THREAD

**Issue by cobraz** [tabetalt/backoffice#57]
TBA

**Comment by seacurrent** [comment]
a shop owner must be able to add deliverymethods. description field and price field, price must be added to checkout total

**Comment by seacurrent** [comment]
![Screenshot 2020-10-23 at 16 35 18](https://user-images.githubusercontent.com/70881117/97017062-c7949280-154d-11eb-9b57-2e834f3679ed.png)
"levereingsmetoder" ( delivery options) is under settings.
Leveringsmetode = name of the delivery option
Pris = price
Stattus = is the option active or not
The ticker is if the product is digital with a digitall delivery. @cobraz probably not in barebone?

**Comment by seacurrent** [comment]
![Screenshot 2020-10-23 at 16 35 26](https://user-images.githubusercontent.com/70881117/97017432-2d811a00-154e-11eb-925c-5de118b8d72e.png)
Leveringsmetode = name of the delivery option
Pris = price
Stattus = is the option active or not
The ticker is if the product is digital with a digitall delivery. @cobraz probably not in barebone?
