### ISSUE TITLE
Product

### ISSUE THREAD

**Issue by cobraz** [tabetalt/backoffice#60]

**Comment by seacurrent** [comment]
This is the standard product information that i stored an shown to customer.

**Comment by seacurrent** [comment]
![Screenshot 2020-10-23 at 16 05 40](https://user-images.githubusercontent.com/70881117/97013818-cd887480-1549-11eb-9aff-c3e07853df7e.png)
This si the basic information (in norwegian: Grunnleggende)

**Comment by seacurrent** [comment]
![Screenshot 2020-10-23 at 16 05 49](https://user-images.githubusercontent.com/70881117/97014053-1ccea500-154a-11eb-99d6-bfcbfd7e3865.png)
This is after you press "beskrivelse" ( description) This is the page with text descriptions

**Comment by seacurrent** [comment]
![Screenshot 2020-10-23 at 16 06 00](https://user-images.githubusercontent.com/70881117/97014806-1b51ac80-154b-11eb-84cd-9bcec215fdd9.png)
This is after you press "lagerbeholding" (Stock). To choose if this product is in stock and #

**Comment by TanyaDolgopolova** [comment]
Okay, I got you

**Comment by seacurrent** [comment]
![Screenshot 2020-10-23 at 16 06 11](https://user-images.githubusercontent.com/70881117/97014955-45a36a00-154b-11eb-80a5-cc0fb0061fa9.png)
This is after you press "Varianter"  (Variations) see also #62

**Comment by seacurrent** [comment]
![Screenshot 2020-10-23 at 16 06 51](https://user-images.githubusercontent.com/70881117/97015271-a763d400-154b-11eb-9104-28a37db71ef9.png)
This is after you press "Etikett og salg" ( Labels and sales) Not sufre if we should implement now. @cobraz ?
