### ISSUE TITLE
Product categories

### ISSUE THREAD

**Issue by cobraz** [tabetalt/backoffice#61]

**Comment by seacurrent** [comment]
To be able to show product of the same category, ex trousers or jacket. Another good word for categories would be Labels, in Git.

**Comment by seacurrent** [comment]
![Screenshot 2020-10-23 at 16 26 17](https://user-images.githubusercontent.com/70881117/97016561-2ad1f500-154d-11eb-9bfd-cd26c0a08050.png)
After pressing "Legg til ny kategori" ( add category)

**Comment by TanyaDolgopolova** [comment]
<img width="571" alt="Screenshot 2020-11-03 at 14 27 14" src="https://user-images.githubusercontent.com/35150766/97985575-1f01f080-1de1-11eb-9b44-c9aa541ea4e6.png">
I have a question about the status field. May it be a regular field or a selection field?

**Comment by seacurrent** [comment]
@TanyaDolgopolova best if this is a selection field, Aktiv/inaktiv (active/inactive) The field is to show if a category is active and should show in the shop

**Comment by TanyaDolgopolova** [comment]
@seacurrent I have a question about under category field. What is the meaning of this field? What should be in this select field?

**Comment by seacurrent** [comment]
Do you mean the field named "underkategori av"?

**Comment by seacurrent** [comment]
@AnneMatilde do you Have a comment?

**Comment by AnneMatilde** [comment]
"Underkategori" is the same as sub category. So the idea is that you can make a main category (clothes) and then a sub category (sweater).

**Comment by TanyaDolgopolova** [comment]
@AnneMatilde Okay, thanks. Also, I have a question about first action button. What should it do?
<img width="507" alt="Screenshot 2020-11-06 at 18 56 33" src="https://user-images.githubusercontent.com/35150766/98393382-ddcc4380-2061-11eb-8e5b-dfa6c90c39a2.png">

**Comment by AnneMatilde** [comment]
This button should open the category in a new window @TanyaDolgopolova .

**Comment by TanyaDolgopolova** [comment]
@AnneMatilde do we have a design for this new window?

**Comment by AnneMatilde** [comment]
No, it opens the actual category page of the shop.
But actually, when I think about it - I think we should just remove this button for now. Its not a very important feature.

**Comment by cobraz** [comment]
I agree with @AnneMatilde, let's remove them for now :)
