### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by cobraz** [tabetalt/backoffice#71]
I think `backoffice` suits much better than `admin`, probably easier to advertise too. 👍 

cc: @AnneMatilde @seacurrent

**Comment by seacurrent** [comment]
I agree

**Comment by seacurrent** [comment]
When er are creating the possibility to administrate client shops. Thst is admin

**Comment by cobraz** [comment]
That makes sense :)

**Comment by cobraz** [comment]
Let's make sure that people are notified before we do anything. @TanyaDolgopolova and @kvokov, can you confirm? :)

**Comment by cobraz** [comment]
We could also name it «console»? What do you think?

**Comment by TanyaDolgopolova** [comment]
Hi, I agree with @cobraz about renaming repository

**Comment by cobraz** [comment]
We've renamed! 🎉
